//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imgs2Epub.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imgs2Epub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 New Chapter 的當地語系化字串。
        /// </summary>
        public static string AddChapDefault {
            get {
                return ResourceManager.GetString("AddChapDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add a New Chapter 的當地語系化字串。
        /// </summary>
        public static string AddChapLabel {
            get {
                return ResourceManager.GetString("AddChapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New Paragraph 的當地語系化字串。
        /// </summary>
        public static string AddParaLabel {
            get {
                return ResourceManager.GetString("AddParaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Photo Files 的當地語系化字串。
        /// </summary>
        public static string AddPhotoLabel {
            get {
                return ResourceManager.GetString("AddPhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album Info. 的當地語系化字串。
        /// </summary>
        public static string AlbumInfo {
            get {
                return ResourceManager.GetString("AlbumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album Project List 的當地語系化字串。
        /// </summary>
        public static string AlbumPrjList {
            get {
                return ResourceManager.GetString("AlbumPrjList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Untitled Album) 的當地語系化字串。
        /// </summary>
        public static string AlbumTitleDefault {
            get {
                return ResourceManager.GetString("AlbumTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album Title 的當地語系化字串。
        /// </summary>
        public static string AlbumTitleLabel {
            get {
                return ResourceManager.GetString("AlbumTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album EPUB Studio 的當地語系化字串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 at 的當地語系化字串。
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name of the Author(s) 的當地語系化字串。
        /// </summary>
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Background Images 的當地語系化字串。
        /// </summary>
        public static string BackgroundImages {
            get {
                return ResourceManager.GetString("BackgroundImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Building the pages for preview... 的當地語系化字串。
        /// </summary>
        public static string BuildPreviewMsg {
            get {
                return ResourceManager.GetString("BuildPreviewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sub-directory for Chapter Files 的當地語系化字串。
        /// </summary>
        public static string ChapDirLabel {
            get {
                return ResourceManager.GetString("ChapDirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Every paragraph is a set of photos, including the date, location, and the description of the photos. 的當地語系化字串。
        /// </summary>
        public static string ChapterPageMsg {
            get {
                return ResourceManager.GetString("ChapterPageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Title of Chapter 的當地語系化字串。
        /// </summary>
        public static string ChapTitleLabel {
            get {
                return ResourceManager.GetString("ChapTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to delete the album? 的當地語系化字串。
        /// </summary>
        public static string ConfirmDeleteAlbum {
            get {
                return ResourceManager.GetString("ConfirmDeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to delete the chapter? 的當地語系化字串。
        /// </summary>
        public static string ConfirmDeleteChapter {
            get {
                return ResourceManager.GetString("ConfirmDeleteChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to remove the album cover? 的當地語系化字串。
        /// </summary>
        public static string ConfirmDeleteCover {
            get {
                return ResourceManager.GetString("ConfirmDeleteCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to delete the paragraph? 的當地語系化字串。
        /// </summary>
        public static string ConfirmDeleteParagraph {
            get {
                return ResourceManager.GetString("ConfirmDeleteParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to delete this photo? 的當地語系化字串。
        /// </summary>
        public static string ConfirmDeletePhoto {
            get {
                return ResourceManager.GetString("ConfirmDeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select the font face, text size and color, and the background, then click Generate. 的當地語系化字串。
        /// </summary>
        public static string CoverPageMsg {
            get {
                return ResourceManager.GetString("CoverPageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Date Stamp and Location of the Photos 的當地語系化字串。
        /// </summary>
        public static string DataLocationLabel {
            get {
                return ResourceManager.GetString("DataLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete the Chapter 的當地語系化字串。
        /// </summary>
        public static string DeleteChapLabel {
            get {
                return ResourceManager.GetString("DeleteChapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete the Album 的當地語系化字串。
        /// </summary>
        public static string DeleteEpubLabel {
            get {
                return ResourceManager.GetString("DeleteEpubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete this Paragraph 的當地語系化字串。
        /// </summary>
        public static string DeleteParaLabel {
            get {
                return ResourceManager.GetString("DeleteParaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete the Photo 的當地語系化字串。
        /// </summary>
        public static string DeletePhotoLabel {
            get {
                return ResourceManager.GetString("DeletePhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deleting the album 的當地語系化字串。
        /// </summary>
        public static string DeletingAlbumMsg {
            get {
                return ResourceManager.GetString("DeletingAlbumMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The directory already exists. 的當地語系化字串。
        /// </summary>
        public static string DirectoryAlreadyExists {
            get {
                return ResourceManager.GetString("DirectoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done 的當地語系化字串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit the Chapter 的當地語系化字串。
        /// </summary>
        public static string EditChapLabel {
            get {
                return ResourceManager.GetString("EditChapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Generate the Cover 的當地語系化字串。
        /// </summary>
        public static string EditCoverLabel {
            get {
                return ResourceManager.GetString("EditCoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit the Album Project 的當地語系化字串。
        /// </summary>
        public static string EditEpubPrjLabel {
            get {
                return ResourceManager.GetString("EditEpubPrjLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit the Photo Info. 的當地語系化字串。
        /// </summary>
        public static string EditPhotoLabel {
            get {
                return ResourceManager.GetString("EditPhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit from Preview 的當地語系化字串。
        /// </summary>
        public static string ExitFromPreview {
            get {
                return ResourceManager.GetString("ExitFromPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export to a File 的當地語系化字串。
        /// </summary>
        public static string ExportEpubLabel {
            get {
                return ResourceManager.GetString("ExportEpubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pick the file name to export to... 的當地語系化字串。
        /// </summary>
        public static string ExportEpubMsg {
            get {
                return ResourceManager.GetString("ExportEpubMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exporting the album to 的當地語系化字串。
        /// </summary>
        public static string ExportingAlbumMsg {
            get {
                return ResourceManager.GetString("ExportingAlbumMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pick the photo file name to export to... 的當地語系化字串。
        /// </summary>
        public static string ExportPhotoMsg {
            get {
                return ResourceManager.GetString("ExportPhotoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The file is exported to: 的當地語系化字串。
        /// </summary>
        public static string FileExportedOK {
            get {
                return ResourceManager.GetString("FileExportedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Generate 的當地語系化字串。
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://www.cyberworlds.net/imgs2epub/manual_en.php 的當地語系化字串。
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pick an image file as the album cover... 的當地語系化字串。
        /// </summary>
        public static string ImportCoverMsg {
            get {
                return ResourceManager.GetString("ImportCoverMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Import an .album.epub File 的當地語系化字串。
        /// </summary>
        public static string ImportEpubLabel {
            get {
                return ResourceManager.GetString("ImportEpubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pick an album epub file to import... 的當地語系化字串。
        /// </summary>
        public static string ImportEpubMsg {
            get {
                return ResourceManager.GetString("ImportEpubMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Importing the album 的當地語系化字串。
        /// </summary>
        public static string ImportingAlbumMsg {
            get {
                return ResourceManager.GetString("ImportingAlbumMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pick photo files to import... 的當地語系化字串。
        /// </summary>
        public static string ImportPhotoMsg {
            get {
                return ResourceManager.GetString("ImportPhotoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading photo files, please wait... 的當地語系化字串。
        /// </summary>
        public static string LoadingPhotos {
            get {
                return ResourceManager.GetString("LoadingPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location(s) of Photography 的當地語系化字串。
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please edit the information and introduction of the album, and add new chapters. You can pick a chapter then rename or edit it, and you can reorder the chapters by dragging. 的當地語系化字串。
        /// </summary>
        public static string MainPageMsg {
            get {
                return ResourceManager.GetString("MainPageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mark the Date: 的當地語系化字串。
        /// </summary>
        public static string MarkDate {
            get {
                return ResourceManager.GetString("MarkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mark the Location 的當地語系化字串。
        /// </summary>
        public static string MarkLocation {
            get {
                return ResourceManager.GetString("MarkLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Untitled Album) 的當地語系化字串。
        /// </summary>
        public static string NewAlbumTitle {
            get {
                return ResourceManager.GetString("NewAlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New Chapter 的當地語系化字串。
        /// </summary>
        public static string NewChapTitle {
            get {
                return ResourceManager.GetString("NewChapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New Album Project 的當地語系化字串。
        /// </summary>
        public static string NewEpubPrjLabel {
            get {
                return ResourceManager.GetString("NewEpubPrjLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No 的當地語系化字串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The name of the sub-directory can not be empty. 的當地語系化字串。
        /// </summary>
        public static string NonEmptyDirNameMsg {
            get {
                return ResourceManager.GetString("NonEmptyDirNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This is not an album file created by this software. 的當地語系化字串。
        /// </summary>
        public static string NotAnAlbumFile {
            get {
                return ResourceManager.GetString("NotAnAlbumFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not implemented yet! 的當地語系化字串。
        /// </summary>
        public static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Online Help 的當地語系化字串。
        /// </summary>
        public static string OnlineHelpLabel {
            get {
                return ResourceManager.GetString("OnlineHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paragraphs (Subset of Photos) 的當地語系化字串。
        /// </summary>
        public static string ParaListLabel {
            get {
                return ResourceManager.GetString("ParaListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Optional Subheading 的當地語系化字串。
        /// </summary>
        public static string ParaSubheadingLabel {
            get {
                return ResourceManager.GetString("ParaSubheadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paragraph Text (Brief of the Photos) 的當地語系化字串。
        /// </summary>
        public static string ParaTextLabel {
            get {
                return ResourceManager.GetString("ParaTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Photos: 的當地語系化字串。
        /// </summary>
        public static string PhotoCountLabel {
            get {
                return ResourceManager.GetString("PhotoCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Photo Dates: 的當地語系化字串。
        /// </summary>
        public static string PhotoDatesLabel {
            get {
                return ResourceManager.GetString("PhotoDatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Label Text: 的當地語系化字串。
        /// </summary>
        public static string PhotoLabelText {
            get {
                return ResourceManager.GetString("PhotoLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Photos (Drag and drop the photo files here) 的當地語系化字串。
        /// </summary>
        public static string PhotoListLabel {
            get {
                return ResourceManager.GetString("PhotoListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preface 的當地語系化字串。
        /// </summary>
        public static string Preface {
            get {
                return ResourceManager.GetString("Preface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Introduction to the Album (Preface) 的當地語系化字串。
        /// </summary>
        public static string PrefaceLabel {
            get {
                return ResourceManager.GetString("PrefaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preview the Album 的當地語系化字串。
        /// </summary>
        public static string PreviewLabel {
            get {
                return ResourceManager.GetString("PreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go Back 的當地語系化字串。
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove the Cover 的當地語系化字串。
        /// </summary>
        public static string RemoveCoverLabel {
            get {
                return ResourceManager.GetString("RemoveCoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove the Photo 的當地語系化字串。
        /// </summary>
        public static string RemovePhoto {
            get {
                return ResourceManager.GetString("RemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rename the Chapter 的當地語系化字串。
        /// </summary>
        public static string RenameChapLabel {
            get {
                return ResourceManager.GetString("RenameChapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replace... 的當地語系化字串。
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rotate 的當地語系化字串。
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save As... 的當地語系化字串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Saving the rotated image... 的當地語系化字串。
        /// </summary>
        public static string SaveRotatedImage {
            get {
                return ResourceManager.GetString("SaveRotatedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Selected Paragraph 的當地語系化字串。
        /// </summary>
        public static string SelectedParagraph {
            get {
                return ResourceManager.GetString("SelectedParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Set the Album Cover 的當地語系化字串。
        /// </summary>
        public static string SetAlbumCover {
            get {
                return ResourceManager.GetString("SetAlbumCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The photo is selected as cover photo of the album, you have to re-generate the cover image on the previous screen. 的當地語系化字串。
        /// </summary>
        public static string SetCoverPrompt {
            get {
                return ResourceManager.GetString("SetCoverPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Table of Contents 的當地語系化字串。
        /// </summary>
        public static string TableOfContents {
            get {
                return ResourceManager.GetString("TableOfContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text Color 的當地語系化字串。
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text Font and Size 的當地語系化字串。
        /// </summary>
        public static string TextFontSize {
            get {
                return ResourceManager.GetString("TextFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 to 的當地語系化字串。
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unsupported file format! 的當地語系化字串。
        /// </summary>
        public static string UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("UnsupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Untitled Chapter) 的當地語系化字串。
        /// </summary>
        public static string UntitledChapTitle {
            get {
                return ResourceManager.GetString("UntitledChapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Cover Image 的當地語系化字串。
        /// </summary>
        public static string UploadCoverLabel {
            get {
                return ResourceManager.GetString("UploadCoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Welcome! Please new or import an album project, or click a listed album then edit it. 的當地語系化字串。
        /// </summary>
        public static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yes 的當地語系化字串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
